# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timeplayer/LayerSettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LayerSettingsDialog(object):
    def setupUi(self, LayerSettingsDialog):
        LayerSettingsDialog.setObjectName("LayerSettingsDialog")
        LayerSettingsDialog.setWindowModality(QtCore.Qt.WindowModal)
        LayerSettingsDialog.resize(302, 306)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            LayerSettingsDialog.sizePolicy().hasHeightForWidth()
        )
        LayerSettingsDialog.setSizePolicy(sizePolicy)
        LayerSettingsDialog.setMinimumSize(QtCore.QSize(0, 0))
        LayerSettingsDialog.setMaximumSize(QtCore.QSize(500, 500))
        LayerSettingsDialog.setBaseSize(QtCore.QSize(300, 185))
        self.gridLayout = QtWidgets.QGridLayout(LayerSettingsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.hispeedBox = QtWidgets.QCheckBox(LayerSettingsDialog)
        self.hispeedBox.setObjectName("hispeedBox")
        self.gridLayout.addWidget(self.hispeedBox, 0, 0, 1, 2)
        self.fademodeBox = QtWidgets.QCheckBox(LayerSettingsDialog)
        self.fademodeBox.setChecked(True)
        self.fademodeBox.setObjectName("fademodeBox")
        self.gridLayout.addWidget(self.fademodeBox, 1, 0, 1, 2)
        self.endpointBox = QtWidgets.QCheckBox(LayerSettingsDialog)
        self.endpointBox.setObjectName("endpointBox")
        self.gridLayout.addWidget(self.endpointBox, 4, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(LayerSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 9, 0, 1, 6)
        self.groupBox = QtWidgets.QGroupBox(LayerSettingsDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet(
            "QGroupBox {border: 2px solid  rgb(131, 131, 131)};"
        )
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(200, 130, 21, 31))
        self.label_4.setObjectName("label_4")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 130, 51, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.xLabelOffsetBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.xLabelOffsetBox.setMinimum(-100)
        self.xLabelOffsetBox.setMaximum(100)
        self.xLabelOffsetBox.setObjectName("xLabelOffsetBox")
        self.verticalLayout.addWidget(self.xLabelOffsetBox)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(130, 130, 51, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.yLabelOffsetBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.yLabelOffsetBox.setMinimum(-100)
        self.yLabelOffsetBox.setMaximum(100)
        self.yLabelOffsetBox.setObjectName("yLabelOffsetBox")
        self.verticalLayout_2.addWidget(self.yLabelOffsetBox)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(230, 130, 39, 41))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelSizeBox = QtWidgets.QSpinBox(self.layoutWidget2)
        self.labelSizeBox.setMinimum(5)
        self.labelSizeBox.setMaximum(50)
        self.labelSizeBox.setProperty("value", 10)
        self.labelSizeBox.setObjectName("labelSizeBox")
        self.verticalLayout_4.addWidget(self.labelSizeBox)
        self.labeltimeBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.labeltimeBox.setGeometry(QtCore.QRect(140, 90, 101, 20))
        self.labeltimeBox.setAccelerated(True)
        self.labeltimeBox.setMaximum(2147483647.0)
        self.labeltimeBox.setProperty("value", 10.0)
        self.labeltimeBox.setObjectName("labeltimeBox")
        self.recentLabelsButton = QtWidgets.QRadioButton(self.groupBox)
        self.recentLabelsButton.setGeometry(QtCore.QRect(140, 60, 80, 17))
        self.recentLabelsButton.setChecked(True)
        self.recentLabelsButton.setObjectName("recentLabelsButton")
        self.allLabelsButton = QtWidgets.QRadioButton(self.groupBox)
        self.allLabelsButton.setGeometry(QtCore.QRect(140, 30, 63, 17))
        self.allLabelsButton.setObjectName("allLabelsButton")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 90, 31, 20))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label.setObjectName("label")
        self.timeunitBox = QtWidgets.QComboBox(self.groupBox)
        self.timeunitBox.setGeometry(QtCore.QRect(58, 90, 81, 20))
        self.timeunitBox.setObjectName("timeunitBox")
        self.timeunitBox.addItem("")
        self.timeunitBox.addItem("")
        self.timeunitBox.addItem("")
        self.timeunitBox.addItem("")
        self.showLabelsBox = QtWidgets.QCheckBox(self.groupBox)
        self.showLabelsBox.setGeometry(QtCore.QRect(10, 30, 102, 17))
        self.showLabelsBox.setObjectName("showLabelsBox")
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 6)

        self.retranslateUi(LayerSettingsDialog)
        self.buttonBox.accepted.connect(LayerSettingsDialog.accept)
        self.buttonBox.rejected.connect(LayerSettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(LayerSettingsDialog)

    def retranslateUi(self, LayerSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        LayerSettingsDialog.setWindowTitle(
            _translate("LayerSettingsDialog", "Layer Settings")
        )
        self.hispeedBox.setText(_translate("LayerSettingsDialog", "Cached Rendering"))
        self.fademodeBox.setText(_translate("LayerSettingsDialog", "Fade older data"))
        self.endpointBox.setText(
            _translate("LayerSettingsDialog", "Show start/end points")
        )
        self.groupBox.setToolTip(
            _translate("LayerSettingsDialog", "Options for label display")
        )
        self.groupBox.setTitle(_translate("LayerSettingsDialog", "Label Options"))
        self.label_4.setText(_translate("LayerSettingsDialog", "Size:"))
        self.label_2.setText(_translate("LayerSettingsDialog", "X offset:"))
        self.label_3.setText(_translate("LayerSettingsDialog", "Y offset:"))
        self.recentLabelsButton.setText(
            _translate("LayerSettingsDialog", "Recent only")
        )
        self.allLabelsButton.setText(_translate("LayerSettingsDialog", "Show All"))
        self.label.setText(_translate("LayerSettingsDialog", "Time:"))
        self.timeunitBox.setItemText(0, _translate("LayerSettingsDialog", "Sec."))
        self.timeunitBox.setItemText(1, _translate("LayerSettingsDialog", "Min."))
        self.timeunitBox.setItemText(2, _translate("LayerSettingsDialog", "Hour"))
        self.timeunitBox.setItemText(3, _translate("LayerSettingsDialog", "Day"))
        self.showLabelsBox.setText(_translate("LayerSettingsDialog", "Show Labels"))
