# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timeplayer/SavedSettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_savedSettingsDialog(object):
    def setupUi(self, savedSettingsDialog):
        savedSettingsDialog.setObjectName("savedSettingsDialog")
        savedSettingsDialog.resize(213, 148)
        self.verticalLayout = QtWidgets.QVBoxLayout(savedSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layerNameLabel = QtWidgets.QLabel(savedSettingsDialog)
        self.layerNameLabel.setObjectName("layerNameLabel")
        self.verticalLayout.addWidget(self.layerNameLabel)
        self.label = QtWidgets.QLabel(savedSettingsDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.yesBox = QtWidgets.QCheckBox(savedSettingsDialog)
        self.yesBox.setObjectName("yesBox")
        self.verticalLayout.addWidget(self.yesBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(savedSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.No | QtWidgets.QDialogButtonBox.Yes
        )
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(savedSettingsDialog)
        self.buttonBox.accepted.connect(savedSettingsDialog.accept)
        self.buttonBox.rejected.connect(savedSettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(savedSettingsDialog)

    def retranslateUi(self, savedSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        savedSettingsDialog.setWindowTitle(
            _translate("savedSettingsDialog", "Load Saved Settings")
        )
        self.layerNameLabel.setText(_translate("savedSettingsDialog", "<layername>"))
        self.label.setText(
            _translate(
                "savedSettingsDialog",
                " has saved settings.  \n"
                "\n"
                "Would you like to load this layer with the saved settings?",
            )
        )
        self.yesBox.setText(
            _translate("savedSettingsDialog", "Yes for all layers with saved settings")
        )
